import test from "node:test";
import assert from "node:assert/strict";
import { mkdtemp, mkdir, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";

import { PartialsHelper } from "../dist/helpers/PartialsHelper.js";
import { StateHelper } from "../dist/helpers/StateHelper.js";

/**
 * Creates the following fixture:
 *
 *   content/home.md
 *   content/docs/page.md
 *   content/docs/codeblocks.md
 *   partials/navigation.md
 */
const setup = async (files = {}) => {
  const root = await mkdtemp(join(tmpdir(), "doctor-partials-"));
  const startFolder = join(root, "content");
  const partialsFolder = join(root, "partials");

  await mkdir(join(startFolder, "docs"), { recursive: true });
  await mkdir(partialsFolder, { recursive: true });

  const defaults = {
    "content/home.md": `---\ntitle: Home\n---\n\nHome`,
    "content/docs/codeblocks.md": `---\ntitle: Codeblocks\n---\n\nCodeblocks`,
    "partials/navigation.md": [
      `## Navigation`,
      ``,
      `- [Home](/home)`,
      `- [Codeblocks](../content/docs/codeblocks)`,
      `- [Current](.)`,
      `- [Doctor](https://github.com/estruyf/doctor)`,
    ].join("\n"),
  };

  for (const [path, contents] of Object.entries({ ...defaults, ...files })) {
    await writeFile(join(root, path), contents, { encoding: "utf-8" });
  }

  const options = {
    startFolder,
    partials: { folder: partialsFolder },
  };

  return { root, startFolder, partialsFolder, options };
};

const cleanup = async (root) => {
  PartialsHelper.reset();
  await rm(root, { recursive: true, force: true });
};

const page = (root, body, frontMatter = `title: Page`) =>
  `---\n${frontMatter}\n---\n\n${body}`;

const processPage = async (root, options, body, frontMatter) => {
  const file = join(root, "content", "docs", "page.md");
  const contents = page(root, body, frontMatter);
  await writeFile(file, contents, { encoding: "utf-8" });

  PartialsHelper.init(options);
  return { file, contents, ...(await PartialsHelper.process(file, contents, options)) };
};

test("process expands an include tag and rebases the links of the partial", async (t) => {
  const { root, options } = await setup();
  t.after(() => cleanup(root));

  const { content } = await processPage(
    root,
    options,
    `# Page\n\n<include file="navigation" />`
  );

  assert.match(content, /## Navigation/);
  // Root relative links resolve from the start folder
  assert.match(content, /\[Home\]\(\.\.\/home\)/);
  // Links of the partial resolve from the folder of the page including it
  assert.match(content, /\[Codeblocks\]\(\.\/codeblocks\)/);
  // A link to the current page keeps pointing at the current page
  assert.match(content, /\[Current\]\(\.\)/);
  // External links are left alone
  assert.match(content, /\[Doctor\]\(https:\/\/github\.com\/estruyf\/doctor\)/);
});

test("process rebases the reference style links and images of a partial", async (t) => {
  const { root, options } = await setup({
    "partials/navigation.md": [
      `![Logo](../assets/logo.png)`,
      ``,
      `[Home][home] and [Codeblocks][codeblocks]`,
      ``,
      `[home]: /home`,
      `[codeblocks]: ../content/docs/codeblocks`,
    ].join("\n"),
  });
  t.after(() => cleanup(root));

  const { content } = await processPage(
    root,
    options,
    `<include file="navigation" />`
  );

  assert.match(content, /!\[Logo\]\(\.\.\/\.\.\/assets\/logo\.png\)/);
  assert.match(content, /^\[home\]: \.\.\/home$/m);
  assert.match(content, /^\[codeblocks\]: \.\/codeblocks$/m);
});

test("process leaves the include tags inside code blocks untouched", async (t) => {
  const { root, options } = await setup();
  t.after(() => cleanup(root));

  const { content } = await processPage(
    root,
    options,
    ['```html', '<include file="navigation" />', '```', '', 'Inline `<include file="navigation" />` too.'].join("\n")
  );

  assert.doesNotMatch(content, /## Navigation/);
  assert.equal(content.match(/<include file="navigation" \/>/g)?.length, 2);
});

test("process injects the configured header and footer partials", async (t) => {
  const { root, options } = await setup({
    "partials/banner.md": `> Generated by Doctor`,
  });
  t.after(() => cleanup(root));

  const { content } = await processPage(
    root,
    { ...options, partials: { ...options.partials, header: "banner", footer: "navigation" } },
    `# Page`
  );

  assert.match(
    content,
    /> Generated by Doctor[\s\S]*# Page[\s\S]*## Navigation/,
    "The header comes before, and the footer after the page content"
  );
});

test("process honors the page level opt-out of the injected partials", async (t) => {
  const { root, options } = await setup({
    "partials/banner.md": `> Generated by Doctor`,
  });
  t.after(() => cleanup(root));

  const withPartials = {
    ...options,
    partials: { ...options.partials, header: "banner", footer: "navigation" },
  };

  const all = await processPage(
    root,
    withPartials,
    `# Page\n\n<include file="banner" />`,
    `title: Page\npartials: false`
  );
  assert.doesNotMatch(all.content, /## Navigation/);
  // The opt-out only applies to the automatically added partials
  assert.equal(all.content.match(/Generated by Doctor/g)?.length, 1);

  const footerOnly = await processPage(
    root,
    withPartials,
    `# Page`,
    `title: Page\npartials:\n  footer: false`
  );
  assert.match(footerOnly.content, /Generated by Doctor/);
  assert.doesNotMatch(footerOnly.content, /## Navigation/);
});

test("process keeps the original hash for pages without partials", async (t) => {
  const { root, options } = await setup();
  t.after(() => cleanup(root));

  const { contents, hash } = await processPage(root, options, `# Page`);

  assert.equal(hash, StateHelper.hashContent(contents));
});

test("process changes the hash of a page when its partial changed", async (t) => {
  const { root, options } = await setup();
  t.after(() => cleanup(root));

  const before = await processPage(
    root,
    options,
    `# Page\n\n<include file="navigation" />`
  );

  assert.notEqual(before.hash, StateHelper.hashContent(before.contents));

  await writeFile(
    join(root, "partials", "navigation.md"),
    `## Navigation\n\n- [Home](/home)`,
    { encoding: "utf-8" }
  );

  const after = await processPage(
    root,
    options,
    `# Page\n\n<include file="navigation" />`
  );

  assert.notEqual(before.hash, after.hash);
});

test("process fails on a missing partial", async (t) => {
  const { root, options } = await setup();
  t.after(() => cleanup(root));

  await assert.rejects(
    () => processPage(root, options, `<include file="does-not-exist" />`),
    /The partial "does-not-exist" .* doesn't exist/
  );
});

test("process fails on partials including each other", async (t) => {
  const { root, options } = await setup({
    "partials/first.md": `<include file="second" />`,
    "partials/second.md": `<include file="first" />`,
  });
  t.after(() => cleanup(root));

  await assert.rejects(
    () => processPage(root, options, `<include file="first" />`),
    /includes itself/
  );
});

test("process fails on an include tag without a file attribute", async (t) => {
  const { root, options } = await setup();
  t.after(() => cleanup(root));

  await assert.rejects(
    () => processPage(root, options, `<include />`),
    /has no "file" attribute/
  );
});

test("getIgnorePatterns only excludes partials stored inside the start folder", async (t) => {
  const { root, startFolder, options } = await setup();
  t.after(() => cleanup(root));

  assert.deepEqual(PartialsHelper.getIgnorePatterns(options), []);

  const inside = {
    startFolder,
    partials: { folder: join(startFolder, "_partials") },
  };
  assert.deepEqual(PartialsHelper.getIgnorePatterns(inside), [
    `${startFolder.replace(/\\/g, "/")}/_partials/**`,
  ]);
});
