import { join } from "path";
import kleur from "kleur";
import { CommandArguments } from "@models";
import { existsAsync, mkdirAsync, writeFileAsync } from "@utils";

export class Workflow {
  private static readonly workflowFolder = join(".github", "workflows");
  private static readonly workflowFile = "doctor.yml";

  /**
   * Creates the GitHub Actions workflow which publishes the documentation.
   * The `.github/workflows` folder is created when it does not exist yet, and
   * an existing workflow file is never overwritten.
   * @param options Command options used to generate the workflow contents.
   * @returns A promise that resolves when the workflow file is in place.
   */
  public static async start(options: CommandArguments) {
    const crntFolder = process.cwd();
    const folderPath = join(crntFolder, this.workflowFolder);
    const filePath = join(folderPath, this.workflowFile);
    const relPath = `${this.workflowFolder.replace(/\\/g, "/")}/${this.workflowFile}`;

    if (await existsAsync(filePath)) {
      console.log(
        kleur.bold().bgYellow().black(` Skipped: `),
        `The "${relPath}" file already exists. Delete or rename it when you want to generate a new one.`
      );
      return;
    }

    if (!(await existsAsync(folderPath))) {
      await mkdirAsync(folderPath, { recursive: true });
    }

    await writeFileAsync(filePath, this.getContents(options), {
      encoding: "utf-8",
    });

    console.log(
      kleur.bold().bgGreen().black(` Created: `),
      `The "${relPath}" workflow file has been created.`
    );
    console.log("");
    console.log(
      `Add the following secrets to your repository before running the workflow: ${this.getRequiredSecrets(
        options
      ).join(", ")}.`
    );
  }

  /**
   * Retrieve the repository secrets which the generated workflow expects.
   * Values which are already known from the `doctor.json` file are passed by
   * the config itself, so they do not need a secret.
   * @param options Command options which can already contain the values.
   * @returns The list of secret names used in the workflow.
   */
  public static getRequiredSecrets(options: CommandArguments): string[] {
    const secrets = [`CERTIFICATE`, `CERTIFICATE_PASSWORD`];

    if (!options.appId) {
      secrets.push(`APP_ID`);
    }

    if (!options.tenant) {
      secrets.push(`TENANT_ID`);
    }

    if (!options.webUrl) {
      secrets.push(`SITE_URL`);
    }

    return secrets;
  }

  /**
   * Generates the contents of the GitHub Actions workflow file.
   * Arguments which are already defined in the `doctor.json` file are left out,
   * as `doctor` picks these up on its own.
   * @param options Command options used to fill in the workflow.
   * @returns The workflow YAML contents.
   */
  public static getContents(options: CommandArguments): string {
    const secrets = this.getRequiredSecrets(options);
    const secretDocs = secrets
      .map((secret) => `#   - ${secret}: ${this.getSecretDescription(secret)}`)
      .join(`\n`);

    const publishArgs = [
      `--certificate "\${{ secrets.CERTIFICATE }}"`,
      `--password "\${{ secrets.CERTIFICATE_PASSWORD }}"`,
    ];

    if (!options.appId) {
      publishArgs.push(`--appId "\${{ secrets.APP_ID }}"`);
    }

    if (!options.tenant) {
      publishArgs.push(`--tenant "\${{ secrets.TENANT_ID }}"`);
    }

    if (!options.webUrl) {
      publishArgs.push(`--url "\${{ secrets.SITE_URL }}"`);
    }

    publishArgs.push(`--retryWhenFailed`);
    publishArgs.push(`--confirm`);

    const publishCommand = publishArgs
      .map((arg, idx) =>
        idx === publishArgs.length - 1
          ? `            ${arg}`
          : `            ${arg} \\`
      )
      .join(`\n`);

    return `# This workflow has been generated by the "doctor workflow" command.
#
# Add the following secrets to your repository before running it:
${secretDocs}
#
# More information: https://github.com/estruyf/doctor

name: Publish documentation

on:
  push:
    branches:
      - main
    paths:
      - "${this.getContentPath(options)}"
  workflow_dispatch:

jobs:
  publish:
    name: Publish the documentation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Install Doctor
        run: npm install -g @estruyf/doctor

      - name: Publish the documentation
        run: |
          doctor publish \\
${publishCommand}
`;
  }

  /**
   * Retrieve the path filter to use for the workflow trigger.
   * @param options Command options containing the content folder.
   * @returns The relative content path, suffixed with a wildcard.
   */
  private static getContentPath(options: CommandArguments): string {
    const folder = (options.startFolderRel || `./src`)
      .replace(/\\/g, "/")
      .replace(/^\.\//, "")
      .replace(/\/$/, "");

    return `${folder || "src"}/**`;
  }

  /**
   * Retrieve the description to document a secret with.
   * @param secret The name of the secret.
   * @returns The description of the secret.
   */
  private static getSecretDescription(secret: string): string {
    switch (secret) {
      case `CERTIFICATE`:
        return `the base64 encoded contents of your certificate (.pfx, .p12, or .pem)`;
      case `CERTIFICATE_PASSWORD`:
        return `the password of your certificate`;
      case `APP_ID`:
        return `the client ID of your Entra ID app registration`;
      case `TENANT_ID`:
        return `the ID of your tenant`;
      case `SITE_URL`:
        return `the URL of the SharePoint site to publish to`;
      default:
        return ``;
    }
  }
}
